#!/usr/bin/env python
"""
Skala Quantum Chemistry Client

This script performs quantum chemistry calculations using Microsoft Skala service.
It converts SMILES strings to 3D molecular structures and runs DFT calculations.

Usage:
    python skala_client.py --smiles "O" --basis def2-tzvp --grid-level superfine
    python skala_client.py --smiles "CCO" --charge 0 --multiplicity 1
    python skala_client.py --smiles "c1ccccc1" --max-scf-steps 100

Author: Generated by Copilot
"""

import os
import sys
import os
import sys
import argparse
import qcelemental as qcel
from skala.foundry import SkalaFoundryClient, SkalaConfig
from rdkit import Chem
from rdkit.Chem import AllChem
import ssl
from io_utils import setup_session_logger, log_message, log_step, log_result, log_error, finalize_session_log

# Disable SSL verification for development
ssl._create_default_https_context = ssl._create_unverified_context


def smiles_to_xyz(smiles: str, optimize: bool = True) -> str:
    """
    Convert a SMILES string to XYZ coordinates.
    
    Args:
        smiles: SMILES string representation of the molecule
        optimize: Whether to optimize the geometry using MMFF (default: True)
    
    Returns:
        XYZ coordinate string in the format expected by qcelemental
        
    Raises:
        ValueError: If the SMILES string is invalid
    """
    # Create molecule from SMILES
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES string: {smiles}")
    
    # Add hydrogens
    mol = Chem.AddHs(mol)
    
    # Generate 3D coordinates
    result = AllChem.EmbedMolecule(mol, randomSeed=42)
    if result != 0:
        raise ValueError(f"Failed to generate 3D coordinates for SMILES: {smiles}")
    
    # Optimize geometry if requested
    if optimize:
        AllChem.MMFFOptimizeMolecule(mol)
    
    # Get the conformer
    conf = mol.GetConformer()
    
    # Build XYZ string
    xyz_lines = []
    for atom in mol.GetAtoms():
        pos = conf.GetAtomPosition(atom.GetIdx())
        symbol = atom.GetSymbol()
        xyz_lines.append(f"{symbol}  {pos.x:.6f}  {pos.y:.6f}  {pos.z:.6f}")
    
    return "\n".join(xyz_lines)


def smiles_to_molecule(smiles: str, charge: int = 0, multiplicity: int = 1, 
                       optimize: bool = True) -> qcel.models.Molecule:
    """
    Convert a SMILES string to a qcelemental Molecule object.
    
    Args:
        smiles: SMILES string representation of the molecule
        charge: Molecular charge (default: 0)
        multiplicity: Spin multiplicity (default: 1)
        optimize: Whether to optimize the geometry (default: True)
    
    Returns:
        qcelemental Molecule object ready for quantum chemistry calculations
    """
    xyz_data = smiles_to_xyz(smiles, optimize=optimize)
    return qcel.models.Molecule.from_data(
        xyz_data, 
        molecular_charge=charge, 
        molecular_multiplicity=multiplicity
    )


def get_client_from_env():
    """
    Get Skala client using Azure ML endpoint authentication.
    
    Environment variables:
        MODEL_ENDPOINT: Azure ML model endpoint resource ID (required)
    
    Returns:
        tuple: (SkalaFoundryClient, endpoint_url)
    """
    model_endpoint = os.environ.get("MODEL_ENDPOINT")
    if not model_endpoint:
        raise ValueError(
            "MODEL_ENDPOINT must be set in environment variables"
        )
    
    # Extract workspace information from the endpoint resource ID
    endpoint_parts = model_endpoint.split('/')
    subscription_id = endpoint_parts[2]
    resource_group = endpoint_parts[4]
    workspace_name = endpoint_parts[8]
    
    # Authenticate with managed identity to retrieve API key
    from azure.identity import DefaultAzureCredential
    credential = DefaultAzureCredential()
    from azure.ai.ml import MLClient
    ml_client = MLClient(credential, subscription_id, resource_group, workspace_name)
    
    # Get the endpoint name from the model endpoint resource ID
    endpoint_name = endpoint_parts[-1]
    
    # Get the endpoint object
    endpoint = ml_client.online_endpoints.get(name=endpoint_name)
    http_endpoint = endpoint.scoring_uri
    
    # Get API key from endpoint
    api_key = ml_client.online_endpoints.get_keys(name=endpoint_name).primary_key
    
    return SkalaFoundryClient(endpoint=http_endpoint, credential=api_key), http_endpoint


def main():
    """
    Main function to run Skala quantum chemistry calculations from command line.
    """
    # Set up logging session
    session_name = "skala_client"
    output_dir = "./outputs"
    os.makedirs(output_dir, exist_ok=True)
    logger = setup_session_logger(session_name, output_dir)
    
    # Parse command line arguments
    parser = argparse.ArgumentParser(
        description="Skala Quantum Chemistry Client - Run DFT calculations on molecules from SMILES strings",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Basic usage
  python skala_client.py --smiles "O"
  python skala_client.py --smiles "CCO"
  python skala_client.py --smiles "c1ccccc1"
  
  # Custom parameters
  python skala_client.py --smiles "CCO" --basis def2-svp --grid-level fine --charge 0 --multiplicity 1
  python skala_client.py --smiles "O" --max-scf-steps 100

Basis Sets:
  Common options: def2-svp, def2-tzvp, def2-tzvpd, def2-qzvp, cc-pvdz, cc-pvtz
  
Grid Levels:
  Options: fine, superfine, ultrafine
        """
    )
    
    # Required arguments
    parser.add_argument(
        "--smiles",
        type=str,
        required=True,
        help="SMILES string representing the molecule (required)"
    )
    
    # Calculation parameters
    parser.add_argument(
        "--basis",
        type=str,
        default="def2-svp",
        help="Basis set for calculation (default: def2-svp)"
    )
    
    parser.add_argument(
        "--grid-level",
        type=str,
        default="fine",
        choices=["fine", "superfine", "ultrafine"],
        help="DFT integration grid level (default: fine)"
    )
    
    parser.add_argument(
        "--max-scf-steps",
        type=int,
        default=80,
        help="Maximum number of SCF iterations (default: 80)"
    )
    
    parser.add_argument(
        "--charge",
        type=int,
        default=0,
        help="Molecular charge (default: 0)"
    )
    
    parser.add_argument(
        "--multiplicity",
        type=int,
        default=1,
        help="Spin multiplicity (default: 1)"
    )
    
    args = parser.parse_args()
    
    try:
        log_step("Initialization", "Starting Skala quantum chemistry calculation", session_name)
        
        # Log input parameters
        log_message(f"SMILES: {args.smiles}", session_name=session_name)
        log_message(f"Basis set: {args.basis}", session_name=session_name)
        log_message(f"Grid level: {args.grid_level}", session_name=session_name)
        log_message(f"Max SCF steps: {args.max_scf_steps}", session_name=session_name)
        log_message(f"Charge: {args.charge}", session_name=session_name)
        log_message(f"Multiplicity: {args.multiplicity}", session_name=session_name)

        # Convert SMILES to molecule
        log_step("SMILES Conversion", "Converting SMILES to 3D molecular structure", session_name)
        molecule = smiles_to_molecule(
            args.smiles,
            charge=args.charge,
            multiplicity=args.multiplicity,
            optimize=True
        )
        log_message("Molecule created successfully!", session_name=session_name)
        log_result("Number of atoms", len(molecule.symbols), session_name=session_name)
        log_result("Molecular formula", molecule.get_molecular_formula(), session_name=session_name)
        log_result("Molecular Geometry", molecule.geometry, session_name=session_name)
        

        # Initialize client
        log_step("Client Initialization", "Initializing Skala client with MODEL_ENDPOINT", session_name)
        client, http_endpoint = get_client_from_env()
        log_message("Successfully authenticated", session_name=session_name)
        log_result("Endpoint", http_endpoint, session_name=session_name)
        
        # Configure calculation
        log_step("Configuration", "Configuring quantum chemistry calculation", session_name)
        config = SkalaConfig(
            basis=args.basis,
            grid_level=args.grid_level,
            max_num_scf_steps=args.max_scf_steps
        )
        log_message("Configuration ready", session_name=session_name)
        
        # Run calculation
        log_step("Calculation", "Running DFT calculation on Skala", session_name)
        log_message("This may take a few moments...", session_name=session_name)
        status = client.run(molecule, config=config)
        
        # Print results
        if status.status == "succeeded":
            log_step("Results", "Calculation completed successfully", session_name)
            log_result("Total Energy (Hartree)", f"{status.output.total_energy:.8f}", session_name=session_name)
            log_result("Status", status.status, session_name=session_name)
        else:
            log_error(f"Calculation failed with status: {status.status}", session_name=session_name)
            if hasattr(status, 'exception') and status.exception:
                log_error(f"Exception: {status.exception}", session_name=session_name)
            raise RuntimeError(f"Calculation failed with status: {status.status}")
        
        # Finalize log
        log_file = finalize_session_log(session_name)
        print(f"\nLog file saved to: {log_file}")
            
    except ValueError as e:
        log_error(f"Input Error: {e}", e, session_name)
        finalize_session_log(session_name)
        sys.exit(1)
    except Exception as e:
        log_error(f"Unexpected Error: {e}", e, session_name)
        import traceback
        traceback.print_exc()
        finalize_session_log(session_name)
        sys.exit(1)


if __name__ == "__main__":
    main()
